name: my-nexcart-web-app

services:
  backend:
    container_name: backend-application
    image: my-nexcart-web-app:v2
    build:
      context: .
      dockerfile: Dockerfile-multi-stage
    ports:
      - "9090:9090"  
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - nexcart-network
   
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nexCart_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ./src:/code
      - app-data:/app     
    
    restart: unless-stopped 
 
      
  db:
    container_name: postgres-db-app
    image: postgres:15-alpine 
    environment:
      POSTGRES_DB: nexCart_db
      # Use env from .env
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      # === Alternative: Use secret as file ===
      #POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    ports:
      - "5432:5432"                  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nexcart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d nexCart_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    # === Using Docker Secrets ===
    secrets:
      - db_password  

volumes:
  postgres-data:
  app-data:

networks:
  nexcart-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt