server:
  port: 9090

spring:
  application:
    name: NextCart

  # datasource:
  #   url: jdbc:postgresql://localhost:5432/nexCart_db
  #   username: postgres
  #   password: root

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexCart_db}
    username: ${DB_USERNAME:postgres}         
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver             

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
