name: Code Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build-docker:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'integration'
    runs-on: ubuntu-latest

    env:
      VERSION: "1.0.${{ github.run_number }}"
      IMAGE_NAME: "my-nexcart-web-app"
      DOCKERHUB_USER: "ullash997"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
        continue-on-error: true

      - name: Scan Dockerfile for Vulnerabilities
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: 'Dockerfile'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      - name: Build Docker Image
        run: |
          docker build --progress=plain --no-cache -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${VERSION} .

      - name: Scan built Docker image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: $DOCKERHUB_USER/$IMAGE_NAME:$VERSION
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${VERSION}