name: Deploy to DEV

on:
  workflow_dispatch:
  push:
    branches: [ test ]
  

jobs:

    env:
      VERSION: "1.0.3"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Stop Existing Containers
        run: |
          docker compose --profile dev down

      - name: Prepare Secrets
        run: |
          mkdir -p secrets
          echo "root" > secrets/db_password.txt
          chmod 600 secrets/db_password.txt

      - name: Start Containers
        run: |
          docker compose --profile dev up -d

      - name: Verify Deployment
        run: |
          docker compose ps
